import CitationChip from "@/components/CitationChip";

export type Citation = {
  doc_id: string;
  issuer: string;
  section: string;
};

export type Confidence = "high" | "medium" | "low";

export type ComplianceAnswer = {
  answer: string;
  citations: Citation[];
  confidence: Confidence;
  refused: boolean;
  // How the answer was produced. Computed server-side on every request and
  // already logged to the `queries` table; surfaced here so the pipeline's
  // behaviour is checkable without database access — which layer refused, how
  // close retrieval actually got, and which provider served it.
  top_similarity?: number | null;
  provider?: string | null;
  refusal_reason?: string | null;
  latency_ms?: number | null;
};

const CONFIDENCE_STYLES: Record<Confidence, { dot: string; chip: string; label: string }> = {
  high: {
    dot: "bg-good-ink",
    chip: "border-good-line bg-good-bg text-good-ink",
    label: "High confidence",
  },
  medium: {
    dot: "bg-warn-ink",
    chip: "border-warn-line bg-warn-bg text-warn-ink",
    label: "Medium confidence",
  },
  low: {
    dot: "bg-bad-ink",
    chip: "border-bad-line bg-bad-bg text-bad-ink",
    label: "Low confidence",
  },
};

function ConfidenceBadge({ confidence }: { confidence: Confidence }) {
  const style = CONFIDENCE_STYLES[confidence];
  return (
    <span
      className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold ${style.chip}`}
    >
      <span className={`h-1.5 w-1.5 rounded-full ${style.dot}`} aria-hidden />
      {style.label}
    </span>
  );
}

function Citations({ citations }: { citations: Citation[] }) {
  if (citations.length === 0) return null;
  return (
    <div className="mt-6 border-t border-line-2 pt-5">
      <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.09em] text-ink-3">
        Sources · {citations.length}
      </p>
      <div className="flex flex-wrap gap-2">
        {citations.map((citation, i) => (
          <CitationChip key={`${citation.doc_id}-${citation.section}-${i}`} citation={citation} />
        ))}
      </div>
    </div>
  );
}

/** Short, human label for what produced the answer. */
function providerLabel(provider: string | null | undefined): string | null {
  if (!provider) return null;
  if (provider.startsWith("meta/")) return "Answered from the index";
  const [vendor, model] = provider.split("/");
  return `${vendor === "gemini" ? "Gemini" : vendor === "groq" ? "Groq" : vendor} · ${model ?? ""}`.trim();
}

const REFUSAL_LABELS: Record<string, string> = {
  below_threshold: "Layer 1 · similarity threshold, no model called",
  model_refused: "Layer 2 · model judged the text insufficient",
};

/**
 * How this answer was produced. Every value here is measured server-side, not
 * inferred in the UI — the retrieval score that decided whether a model was
 * called at all, which refusal layer fired, which provider actually served it
 * (the failover is real, so this genuinely varies), and end-to-end latency.
 *
 * Collapsed by default: useful to anyone evaluating the retrieval behaviour,
 * noise to someone who just wants the compliance answer.
 */
function Diagnostics({ result }: { result: ComplianceAnswer }) {
  const provider = providerLabel(result.provider);
  const hasAny =
    result.top_similarity != null ||
    provider !== null ||
    result.latency_ms != null ||
    result.refusal_reason != null;
  if (!hasAny) return null;

  return (
    <details className="group mt-5 border-t border-line-2 pt-4">
      <summary
        className="cursor-pointer list-none text-[10px] font-semibold uppercase tracking-[0.09em]
                   text-ink-3 outline-none transition-colors hover:text-ink-2
                   focus-visible:ring-2 focus-visible:ring-accent/40"
      >
        <span className="inline-block transition-transform group-open:rotate-90">›</span> How this
        answer was produced
      </summary>

      <dl className="mt-3 grid grid-cols-[auto_1fr] gap-x-4 gap-y-1.5 text-[12.5px]">
        {result.top_similarity != null && (
          <>
            <dt className="text-ink-3">Top match</dt>
            <dd className="tabular-nums text-ink-2">
              {result.top_similarity.toFixed(4)} cosine similarity
            </dd>
          </>
        )}
        {provider && (
          <>
            <dt className="text-ink-3">Generated by</dt>
            <dd className="text-ink-2">{provider}</dd>
          </>
        )}
        {result.refusal_reason && (
          <>
            <dt className="text-ink-3">Declined at</dt>
            <dd className="text-ink-2">
              {REFUSAL_LABELS[result.refusal_reason] ?? result.refusal_reason}
            </dd>
          </>
        )}
        {result.latency_ms != null && (
          <>
            <dt className="text-ink-3">Latency</dt>
            <dd className="tabular-nums text-ink-2">{result.latency_ms} ms</dd>
          </>
        )}
      </dl>
    </details>
  );
}

export default function AnswerCard({ result }: { result: ComplianceAnswer }) {
  // The refused state gets its own surface treatment — warm tint, ruled left
  // edge, warning glyph and an explicit heading — so "the documents don't cover
  // this" reads instantly, rather than depending on the reader parsing prose.
  if (result.refused) {
    return (
      <article
        className="fade-rise overflow-hidden rounded-2xl border border-warn-line bg-warn-bg
                   shadow-card"
      >
        <div className="border-l-[3px] border-warn-ink/40 px-6 py-5 sm:px-7 sm:py-6">
          <header className="mb-3 flex items-center gap-2.5">
            <span
              aria-hidden
              className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full
                         bg-warn-ink/12 text-[13px] font-bold text-warn-ink"
            >
              !
            </span>
            <h2 className="text-[15px] font-semibold tracking-[-0.01em] text-warn-ink">
              Not covered by these documents
            </h2>
          </header>
          <p className="whitespace-pre-wrap text-[15px] leading-[1.65] text-ink">
            {result.answer}
          </p>
          <Citations citations={result.citations} />
          <Diagnostics result={result} />
        </div>
      </article>
    );
  }

  return (
    <article
      className="fade-rise rounded-2xl border border-line bg-surface px-6 py-6 shadow-card
                 sm:px-7 sm:py-7"
    >
      <p className="whitespace-pre-wrap text-[16px] leading-[1.65] tracking-[-0.005em] text-ink">
        {result.answer}
      </p>
      <div className="mt-5">
        <ConfidenceBadge confidence={result.confidence} />
      </div>
      <Citations citations={result.citations} />
      <Diagnostics result={result} />
    </article>
  );
}
